legacyDaemonsetAPI: false
compatWithCPUManager: false
migStrategy: none

image:
  pullPolicy: IfNotPresent

namespace: kube-system

resources: {}

nodeSelector: {}

affinity: {}

tolerations:
  # This toleration is deprecated. Kept here for backward compatibility
  # See https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
  - key: CriticalAddonsOnly
    operator: Exists
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule
